### PR TITLE
Update plank-holders.md

### PR DESCRIPTION
**Pull request by bytetheio**

### CODE REVIEW

**Review by jordangov — APPROVED** [review]

**Comment by bytetheio** [comment]
Anyway to get this badge mailed to me?

**Comment by bytetheio** [comment]
@jordangov

**Comment by jordangov** [comment]
@bytetheio Sorry, I'm not sure if this is possible. @jring-ncd may know.

**Comment by bytetheio** [comment]
Thanks for the reply @jordangov. It would be really cool to have a badge, I know you guys ran out of them at DEFCON. @jring-ncd if this is possible in any way I would really appreciate it. I don't mind paying shipping costs.

**Pull request merged**
